import fetch from 'node-fetch';
const { WA_DEFAULT_EPHEMERAL } = (await import('@adiwajshing/baileys')).default;

let handler = async (m) => {
    let who;
    if (m.isGroup) who = m.mentionedJid[0] ? m.mentionedJid[0] : m.sender;
    else who = m.sender;
    let user = global.db.data.users[who];
    
    let anu = pickRandom(global.bacot);
    const text = `───────〔 𝗕𝗔𝗖𝗢𝗧 〕───────\n${anu}`;
    const message = {
        text,
        replyTo: m.quoted ? m.quoted : false,
        ephemeral: WA_DEFAULT_EPHEMERAL,
    };
      if (m.quoted) {
        conn.reply(m.chat, message);
    } else {
        conn.sendMessage(m.chat, message);
    }
};

handler.help = ['bacot'];
handler.tags = ['quotes'];
handler.command = /^(bacot)$/i;
handler.owner = false;
handler.mods = false;
handler.premium = false;
handler.group = false;
handler.private = false;
handler.admin = false;
handler.botAdmin = false;
handler.fail = null;
export default handler;
function pickRandom(list) {
  return list[Math.floor(list.length * Math.random())];
}
global.bacot = [
'Kamu suka kopi nggak? Aku sih suka. Tau kenapa alesannya? Kopi itu ibarat kamu, pahit sih tapi bikin candu jadi pingin terus.',
'Gajian itu kayak mantan ya? Bisanya cuman lewat sebentar saja.',
'Kata pak haji, cowok yang nggak mau pergi Sholat Jumat disuruh pakai rok aja.',
'Kamu tahu mantan nggak? Mantan itu ibarat gajian, biasa numpang lewat dong di kehidupan kita.',
'Aku suka kamu, kamu suka dia, tapi dia sayangnya nggak ke kamu. Wkwkw lucu ya? Cinta serumit ini.',
'Google itu hebat ya? Tapi sayang sehebat-hebatnya Google nggak bisa menemukan jodoh kita.',
'Terlalu sering memegang pensil alis dapat membuat mata menjadi buta, jika dicolok-colokkan ke mata.',
'Saya bekerja keras karena sadar kalau uang nggak punya kaki buat jalan sendiri ke kantong saya.',
'Jika kamu tak mampu meyakinkan dan memukau orang dengan kepintaranmu, bingungkan dia dengan kebodohanmu.',
'Selelah-lelahnya bekerja, lebih lelah lagi kalau nganggur.',
'Kita hidup di masa kalau salah kena marah, pas bener dibilang tumben.',
'Nggak ada bahu pacar? Tenang aja, masih ada bahu jalan buat nyandar.',
'Mencintai dirimu itu wajar, yang gak wajar mencintai bapakmu.',
'Katanya enggak bisa bohong. Iyalah, mata kan cuma bisa melihat.',
'Madu di tangan kananmu, racun di tangan kirimu, jodoh tetap di tangan tuhan.',
'Selingkuh terjadi bukan karena ada niat, selingkuh terjadi karna pacar kamu masih laku.',
'Netizen kalau senam jempol di ponsel nggak pakai pendinginan, pantes komennya bikin panas terus.',
'Jodoh memang enggak kemana, tapi saingannya ada dimana-mana.',
'Perasaan aku salah terus di matamu. Kalu gitu, besok aku pindah ke hidungmu.',
'Jomblo tidak perlu malu, jomblo bukan berarti tidak laku, tapi memang tidak ada yang mau.',
'Jika doamu belum terkabul maka bersabar, ingatlah bahwa yang berdoa bukan cuma kamu!',
'Masih berharap dan terus berharap lama-lama aku jadi juara harapan.',
'Manusia boleh berencana, tapi akhirnya saldo juga yang menentukan.',
'Statusnya rohani, kelakuannya rohalus.',
'Kegagalan bukan suatu keberhasilan.',
'Tadi mau makan bakso, cuma kok panas banget, keliatannya baksonya lagi demam.',
'Aku juga pernah kaya, waktu gajian.',
'Aku diputusin sama pacar karena kita beda keyakinan. Aku yakin kalau aku ganteng, tapi dia enggak.',
'Masa depanmu tergantung pada mimpimu, maka perbanyaklah tidur.',
'Seberat apapun pekerjaanmu, akan semakin ringan jika tidak dibawa.',
'Jangan terlalu berharap! nanti jatuhnya sakit!',
'Ingat! Anda itu jomblo',
'Gak tau mau ngetik apa',
'Nggak usah ganteng atau cantik, yang penting jadi diri sendiri. Tapi kalau bisa sih ganteng atau cantik.',
'Jomblo itu kayak WiFi, kadang koneksinya kuat, kadang nggak ada sinyal sama sekali.',
'Jangan diem-diem ngarep, lebih baik diem-diem belajar biar kelak nggak diem-diem ngarep.',
'Kalau makan sate pake bumbu kecap, kenapa kalau makan ketoprak nggak pake bumbu kopi?',
'Pacaran itu kayak main game, kalau nggak serius ya habisin waktu aja.',
'Tahun ini aku cuma butuh dua hal: kesabaran dan uang.',
'Kalau kamu bukan kopi, jangan ngatur moodku.',
'Ketika hidup memberimu lemon, jual aja dan beli kopi.',
'Ketika pacar ngambek, tinggalin aja. Satu-satunya yang boleh ngambek itu WiFi.',
'Cinta itu kayak makanan pedas. Awalnya kerasa enak, tapi lama-lama bisa bikin perih.',
'Jomblo itu lebih hemat, nggak perlu beli cincin, nggak perlu beli baju seragam, dan nggak perlu beli hadiah ulang tahun.',
'Patah hati itu kayak ngupil, sakitnya cuma sebentar tapi rasanya enggak enak.',
'Mending jomblo daripada jadi pelarian.',
'Mencari jodoh itu kayak cari wifi di mall, tampilan banyak, tapi yang free cuma satu.',
'Kadang galau cuma butuh teman curhat, tapi teman curhat malah bilang, "Habisin aja masalahnya sama mie instan."',
'Masa lalu itu kayak WiFi, jika kamu tahu passwordnya, kamu akan terhubung kembali.',
'Jika kamu lagi down, ingatlah bahwa kucing selalu bersih dengan menjilat dirinya sendiri.',
'Bekerja itu kayak nonton film horor, awalnya seru tapi akhirnya bisa bikin nggak tidur semalaman.',
'Kalau kamu diputusin, jangan sedih. Ingat, ada banyak makanan enak di dunia ini.',
'Jodoh nggak kemana, tapi kamu tetap harus jalan-jalan biar ketemu.',
"Jomblo itu kayak laptop, lebih berat beban kerjanya tapi nggak ada yang ngatur password.",
"Hidup ini penuh warna, tapi jangan sampe kamu lupa nge-charge baterai.",
"Cinta itu kayak musik, bisa bikin hati bergetar tapi juga bisa bikin telinga sakit.",
"Lebih baik makan mie instan sendirian daripada makan steak bareng mantan.",
"Kadang aku bertanya-tanya, kenapa cinta itu nggak secepat koneksi internet.",
"Kalau kebahagiaan ada di ujung pelukan, mending aku beli bantal baru.",
"Jika kamu nggak bisa mencintai dirimu sendiri, bagaimana kamu bisa mencintai orang lain?",
"Sebaiknya jangan berharap terlalu banyak, nanti bisa bikin sakit hati.",
"Ketika orang berkata 'move on', mungkin mereka belum pernah nonton film favoritnya di TV.",
"Hidup ini seperti buku, kamu nggak akan tahu apa yang ada di halaman berikutnya.",
"Jika kamu lagi down, cobalah berjalan-jalan. Mungkin kamu bisa menemukan kucing lucu di sepanjang jalan.",
"Pacar itu seperti bunga, harus disiram dengan perhatian dan diberi pupuk cinta.",
"Jika kamu merasa lelah, ingatlah bahwa kucing bisa tidur selama 16 jam sehari.",
"Ketika kamu merasa down, makan cokelat. Kadang cokelat lebih efektif daripada kata-kata.",
"Hidup itu seperti balon, bisa hancur kapan saja tapi kita tetap harus meneruskan perjalanan.",
"Patah hati itu kayak botol ketchup yang susah keluar isinya, tapi kalau udah keluar ya nyesek aja.",
"Jomblo itu seperti arti dari 'LOL'—Laba-laba Orang Lucu.",
"Cinta itu kayak wifi di restoran cepat habis.",
"Kadang galau itu baik, jadi inget kalau kita punya hati.",
"Orang pandai itu kayak WiFi di kampung, susah dicari.",
"Jika kamu stress, coba minum air. Air putih bisa membuatmu lebih jernih, seperti pikiran setelah minum kopi.",
"Cinta itu seperti bunga, bisa indah tapi kalau dibiarkan terlalu lama bisa layu.",
"Lebih baik jadi orang bodoh yang bahagia daripada jadi orang pintar yang galau terus.",
"Pacar itu seperti bensin, harus diisi ulang terus biar jalan terus.",
"Berbicara tentang masalah, kadang-kadang cukup membantu. Tapi makan es krim bisa membantu lebih baik.",
"Kadang cinta itu seperti belanja online, lihat-lihat doang nggak jadi beli.",
"Jika kamu merasa down, coba deh makan cokelat. Cokelat itu seperti peluk hangat untuk perut.",
"Masa depanmu bukanlah produk yang bisa kamu beli diskon, tapi kamu yang harus bekerja keras untuk menciptakannya.",
"Kalau ada orang yang nggak suka sama kamu, jangan khawatir. Bukan kamu salah, mereka aja yang belum paham.",
"Jika hidupmu adalah buku, pastikan ceritanya menarik. Jangan biarkan ada halaman kosong.",
"Hidup ini seperti ponsel, kalau kamu nggak ngecas, nanti mati.",
"Jomblo bukanlah status, tapi posisi untuk mencari yang lebih baik.",
"Ketika orang berkata 'move on', mereka kayak guru yang ngasih PR sambil ketawa-ketawa.",
"Jika kamu merasa kesepian, ingatlah bahwa kucing selalu siap untuk dipeluk.",
"Patah hati itu seperti batu bata, berat di dada tapi bisa dijadikan fondasi yang kuat.",
"Jika kamu merasa down, cobalah mendengarkan lagu favoritmu. Musik itu seperti obat penenang.",
"Cinta itu seperti hujan, kadang datang tiba-tiba dan bikin bingung harus ngapain.",
"Ketika hidup memberimu lemon, jangan lupa kalau kamu masih punya gula untuk membuat lemonade.",
"Pacar itu seperti ponsel, kadang dipake terus, kadang malah ditinggal di rumah.",
"Jika kamu nggak tahu harus ngomong apa, coba deh bilang 'Halo'.",
"Cinta itu seperti kopi, pahit tapi bikin semangat.",
"Ketika orang bilang 'cukup', itu artinya belum selesai tapi sudah nggak tahan.",
"Lebih baik jomblo daripada pacaran sama orang yang nggak serius.",
"Jika kamu merasa capek, istirahatlah. Kamu bukan robot yang bisa terus bekerja tanpa henti.",
"Hidup itu seperti gulali, manis di awal tapi habis sebentar.",
"Jika kamu ingin berubah, kamu harus siap untuk keluar dari zona nyamanmu.",
"Patah hati itu kayak nongkrong di pinggir jalan, sakit tapi pasti ada yang lewat.",
"Cinta itu seperti masakan, terkadang harus tambah garam, terkadang harus tambah cinta.",
"Lebih baik terlambat daripada terlihat norak.",
"Jika kamu merasa jatuh, ingatlah bahwa ada banyak orang yang siap membantumu bangkit.",
"Orang yang nggak pernah salah itu seperti hantu, cuma ada di cerita.",
"Hidup itu seperti roller coaster, naik turun tanpa henti. Tapi ingat, kamu yang pegang kendali.",
"Pacar itu seperti kacamata, ada yang bikin tampilan lebih keren tapi ada juga yang bikin pusing.",
"Ketika orang berkata 'I'm fine', mungkin itu artinya 'Tolong peluk aku'.",
"Jika kamu suka seseorang, katakanlah sebelum dia suka sama orang lain.",
"Cinta itu seperti kunci, bisa membuka hati tapi juga bisa mengunci.",
"Lebih baik jomblo daripada jadi pelarian seseorang.",
"Jika kamu ingin bahagia, jangan terlalu sering membandingkan hidupmu dengan orang lain.",
"Hidup ini seperti komputer, kadang crash tapi selalu ada tombol restart.",
"Ketika semuanya terasa berat, ingatlah bahwa matahari selalu terbit setiap pagi.",
"Pacar itu kayak wifi di tempat umum, sering nggak nyambung.",
"Jika kamu merasa takut, coba deh berbicara dengan seseorang. Terkadang hanya perlu didengarkan.",
"Cinta itu seperti musim hujan, kadang datang tanpa undangan.",
"Hidup itu seperti makanan, bisa enak atau tidak, tergantung cara kamu mengolahnya.",
"Ketika kamu merasa kalah, ingatlah bahwa kegagalan bukan akhir dari segalanya.",
"Jika kamu nggak tahu harus ngomong apa, coba deh senyum. Senyum itu universal.",
"Cinta itu seperti makanan, kalau nggak dicicipi nggak akan tahu enak atau nggak.",
"Ketika orang berkata 'sudahlah', itu artinya kamu salah tapi mereka juga nggak mau ribut.",
"Hidup ini seperti buku, setiap halaman adalah petualangan baru.",
"Jika kamu merasa lelah, istirahatlah. Bahkan baterai ponsel juga butuh di-charge.",
"Pacar itu seperti ponsel, kalau nggak hati-hati bisa jatuh dan pecah.",
"Jika kamu ingin lebih baik, mulailah dengan berhenti melakukan hal yang membuatmu buruk.",
"Cinta itu seperti hujan, bisa bikin basah tapi juga bisa bikin segar.",
"Hidup ini seperti puzzle, harus merangkai potongan-potongan menjadi satu gambar utuh.",
"Ketika kamu merasa sendiri, ingatlah bahwa ada teman yang siap mendengarkanmu.",
"Patah hati itu seperti botol minuman yang pecah, kadang repot nyari tempat buangnya.",
"Jika kamu ingin berubah, mulailah dari dirimu sendiri. Kamu bukan tukang sulap.",
"Cinta itu seperti kunci, harus sesuai ukuran untuk bisa membuka hati.",
"Hidup ini seperti taman bermain, ada yang asyik, ada yang menakutkan, tapi kamu yang pilih.",
"Jika kamu merasa terjatuh, ingatlah bahwa kamu bisa bangkit lagi.",
"Ketika semuanya terasa salah, coba deh istirahat sejenak. Kebiasaan buruk juga butuh cuti.",
"Pacar itu seperti gadget, kadang butuh di-refresh biar nggak lemot.",
"Jika kamu ingin meraih impianmu, berani keluar dari zona nyaman.",
"Hidup ini seperti permainan, ada level sulit tapi juga ada level menyenangkan.",
"Ketika kamu merasa kecewa, ingatlah bahwa hidup nggak selalu sesuai ekspektasi.",
"Cinta itu seperti musik, ada yang rock, ada yang jazz, tapi semuanya bisa membuat hati bergetar.",
"Ketika hidup memberimu jeruk, coba buatlah jus jeruk yang segar.",
"Pacar itu seperti sepatu, harus nyaman saat dipakai.",
"Jika kamu merasa bingung, coba deh tanya orang lain. Bisa jadi mereka punya jawaban.",
"Hidup ini seperti film, kamu yang pilih peran apa yang akan kamu mainkan.",
"Ketika orang berkata 'sabar ya', itu artinya kamu udah lama bikin mereka sabar.",
"Jika kamu ingin merubah duniamu, mulailah dengan merubah pikiranmu.",
"Pacar itu seperti ponsel, sering dipake terus tapi kadang lupa nge-charge.",
"Cinta itu seperti air, kalau dibiarkan terlalu lama bisa basi.",
"Ketika kamu merasa sedih, ingatlah bahwa matahari juga nggak bisa bersinar setiap hari.",
"Hidup ini seperti labirin, kadang harus putar-putar biar tahu jalan keluarnya.",
"Jika kamu ingin bahagia, tinggalkan hal yang membuatmu sedih.",
"Pacar itu seperti wifi di tempat umum, sering nggak bisa nyambung.",
"Jika kamu merasa kesepian, cari teman yang bisa membuatmu tertawa.",
"Hidup ini seperti taman bunga, ada yang indah, ada yang berduri.",
"Ketika semuanya terasa berat, ingatlah bahwa kamu punya kekuatan untuk menghadapinya.",
"Patah hati itu kayak pisang yang kejatuhan, nggak enak tapi masih bisa dimakan.",
"Jika kamu nggak tahu harus ngomong apa, coba deh dengerin cerita orang lain.",
"Hidup ini seperti buku, setiap halaman adalah pelajaran baru.",
"Ketika kamu merasa lelah, istirahatlah. Bahkan tumbuhan pun perlu tidur.",
"Pacar itu kayak baterai, harus di-charge terus biar nggak mati.",
"Jika kamu ingin sukses, jangan takut mencoba dan gagal.",
"Hidup ini seperti perjalanan, kadang harus melewati jalan yang berliku.",
"Ketika semuanya terasa sia-sia, ingatlah bahwa setiap usaha pasti ada hasilnya.",
"Cinta itu seperti angin, kadang datang pelan, kadang datang kencang.",
"Pacar itu seperti komputer, harus di-refresh biar nggak lemot.",
"Jika kamu merasa terjatuh, ingatlah bahwa kamu punya kekuatan untuk bangkit kembali.",
"Hidup ini seperti bermain game, ada level susah tapi juga ada level seru.",
"Ketika kamu merasa kesal, coba deh dengerin lagu favoritmu. Musik bisa meredakan emosi.",
"Pacar itu seperti film, kadang adegan cinta, kadang adegan drama.",
"Jomblo itu seperti kertas putih, kamu yang bisa mengisi dengan cerita apa pun.",
"Hidup ini seperti novel, setiap halaman adalah petualangan baru.",
"Cinta itu seperti bunga mawar, indah tapi ada duri-durinya.",
"Pacar itu seperti bintang, kadang bersinar terang, kadang juga redup.",
"Jika kamu ingin bahagia, hargai dirimu sendiri sebelum mencari pengakuan dari orang lain.",
"Ketika kamu merasa lelah, istirahatlah. Bahkan bunga juga butuh tidur.",
"Hidup ini seperti taman bunga, ada bunga yang mekar dan ada bunga yang layu.",
"Cinta itu seperti api, bisa memberi cahaya tapi juga bisa membakar.",
"Pacar itu seperti musik, bisa membuatmu merasa bersemangat atau sedih.",
"Jika kamu nggak tahu harus ngomong apa, coba deh ceritakan hari kamu.",
"Ketika kamu merasa kesepian, cari teman yang bisa membuatmu tertawa.",
"Hidup ini seperti ponsel, kadang butuh di-refresh agar tetap berjalan lancar.",
"Lebih baik jomblo daripada terjebak dalam hubungan yang nggak bahagia.",
"Cinta itu seperti hujan, kadang bisa bikin basah tapi juga bisa bikin segar.",
"Pacar itu seperti kamera, kadang harus di-fokus supaya hasilnya bagus.",
"Jika kamu ingin sukses, berani keluar dari zona nyaman adalah langkah pertama.",
"Ketika kamu merasa kesal, ingatlah bahwa marah hanya akan membuatmu lelah.",
"Cinta itu seperti sinar matahari, selalu ada walaupun kadang tertutup awan.",
"Pacar itu seperti novel, kadang bikin terbawa emosi tapi kadang juga bikin tertawa.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang hobi atau minatnya.",
"Ketika kamu merasa bingung, ingatlah bahwa ada banyak orang yang siap membantu.",
"Hidup ini seperti pantai, kadang ada pasir, kadang ada ombak, tapi selalu indah.",
"Cinta itu seperti pelangi, indah tapi nggak selalu ada setiap hari.",
"Pacar itu seperti makanan enak, bisa bikin ketagihan tapi jangan sampai kebanyakan.",
"Jika kamu ingin merubah duniamu, mulailah dari pikiranmu.",
"Ketika kamu merasa lelah, istirahatlah. Bahkan bintang pun butuh istirahat di siang hari.",
"Hidup ini seperti roller coaster, ada momen naik dan ada momen turun.",
"Pacar itu seperti pakaian, kadang harus dipilih dengan hati-hati agar cocok.",
"Jika kamu nggak tahu harus ngomong apa, coba deh mendengarkan dengan baik.",
"Ketika kamu merasa frustasi, ingatlah bahwa kamu punya kekuatan untuk menghadapinya.",
"Hidup ini seperti permainan kartu, kadang kamu harus mengambil risiko.",
"Cinta itu seperti bunga matahari, selalu mengikuti cahaya dan berputar.",
"Pacar itu seperti angin, bisa memberi kesejukan tapi juga bisa membuat kedinginan.",
"Jika kamu ingin bahagia, belajarlah untuk bersyukur atas apa yang kamu miliki sekarang.",
"Ketika kamu merasa kesepian, ingatlah bahwa ada banyak hal lain yang bisa membuatmu bahagia.",
"Hidup ini seperti teka-teki, kamu yang mencari jawaban yang tepat.",
"Cinta itu seperti cokelat, bisa bikin senyum dan rasanya manis.",
"Pacar itu seperti permen, kadang membuatmu bahagia tapi kadang juga buat pusing.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang liburan impian mereka.",
"Ketika kamu merasa lelah, ingatlah bahwa istirahat adalah hakmu.",
"Hidup ini seperti tarian, kamu yang menentukan gerakannya.",
"Cinta itu seperti mawar putih, simbol kesucian dan keabadian.",
"Pacar itu seperti ponsel, kalau terlalu sering digunakan bisa bikin kehabisan baterai.",
"Jika kamu ingin merubah duniamu, mulailah dengan merubah kebiasaanmu.",
"Ketika kamu merasa kesal, ingatlah bahwa setiap masalah memiliki solusi.",
"Hidup ini seperti cuaca, kadang cerah kadang mendung, tapi selalu berubah.",
"Cinta itu seperti air, bisa mengalir dan memberi kehidupan.",
"Pacar itu seperti bunga sakura, indah tapi hanya bersemi dalam waktu yang singkat.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang rencana masa depannya.",
"Ketika kamu merasa cemas, ingatlah bahwa kamu punya kekuatan untuk mengatasi rasa takutmu.",
"Hidup ini seperti puzzle, kamu yang harus merangkai potongan-potongannya.",
"Cinta itu seperti surga, tempat di mana hati dan jiwa bersatu.",
"Pacar itu seperti cermin, bisa memantulkan siapa kamu sebenarnya.",
"Jika kamu ingin sukses, belajarlah dari kegagalan dan terus maju.",
"Ketika kamu merasa bahagia, berbagilah dengan orang lain untuk membuatnya berlipat ganda.",
"Hidup ini seperti musik, kadang kencang dan berisik, kadang juga lembut dan menenangkan.",
"Cinta itu seperti bintang jatuh, datang tiba-tiba dan membuatmu terpana.",
"Pacar itu seperti mata air, bisa menyegarkan tapi jangan sampai kehabisan.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang hal-hal yang disukainya.",
"Ketika kamu merasa kesepian, ingatlah bahwa ada banyak cara untuk bersosialisasi.",
"Hidup ini seperti petualangan, selalu ada hal baru yang menunggu untuk diexplore.",
"Cinta itu seperti mimpi indah, membuatmu tersenyum tanpa sadar.",
"Pacar itu seperti kanvas kosong, kamu yang bisa menciptakan gambar indah di dalamnya.",
"Jika kamu ingin bahagia, belajarlah untuk menerima dirimu apa adanya.",
"Ketika kamu merasa lelah, ingatlah bahwa kamu punya hak untuk beristirahat.",
"Hidup ini seperti pohon, perlu dijaga agar tetap tumbuh dan berbuah.",
"Cinta itu seperti keajaiban, datang tanpa diundang tapi bisa mengubah segalanya.",
"Pacar itu seperti kunci, bisa membuka hatimu tapi juga bisa membuatmu terkurung.",
"Jika kamu nggak tahu harus ngomong apa, coba deh ceritakan hal lucu yang pernah kamu alami.",
"Ketika kamu merasa bingung, ingatlah bahwa ada banyak jawaban yang bisa kamu temukan.",
"Hidup ini seperti peta, kamu yang menentukan arah dan tujuanmu.",
"Cinta itu seperti cahaya bulan, selalu ada walaupun kadang terhalang awan.",
"Pacar itu seperti makanan favorit, selalu ada saat kamu butuhkan.",
"Jika kamu ingin sukses, terus belajar dan berusaha menjadi lebih baik.",
"Ketika kamu merasa kesal, cobalah bernapas dalam-dalam dan mengendalikan emosimu.",
"Hidup ini seperti lukisan, kamu yang bisa memilih warna dan gambar yang ingin kamu ciptakan.",
"Cinta itu seperti lagu, kadang berirama ceria dan kadang melankolis.",
"Pacar itu seperti pelukan hangat, membuatmu merasa aman dan nyaman.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang pandangannya terhadap dunia.",
"Ketika kamu merasa lelah, ingatlah bahwa kamu punya kemampuan untuk mengisi ulang energi.",
"Hidup ini seperti perjalanan, ada banyak tempat yang bisa kamu eksplorasi.",
"Cinta itu seperti air hujan, bisa membuat tanah menjadi subur dan hidup.",
"Pacar itu seperti cerita, kadang ada konflik tapi yang penting ada akhir yang bahagia.",
"Jika kamu ingin merubah duniamu, mulailah dengan mempercayai dirimu sendiri.",
"Ketika kamu merasa kesepian, cobalah menghubungi teman atau keluargamu.",
"Hidup ini seperti kolam renang, kadang kamu harus melompat dari papan dan menghadapi ketakutanmu.",
"Cinta itu seperti misteri, ada yang belum terungkap dan bisa membuatmu penasaran.",
"Pacar itu seperti matahari terbenam, indah tapi hanya bertahan sebentar.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang cita-citanya.",
"Ketika kamu merasa frustasi, ingatlah bahwa kamu punya kekuatan untuk mengubah situasi.",
"Hidup ini seperti bermain catur, kamu harus membuat langkah cerdas untuk mencapai tujuanmu.",
"Cinta itu seperti pohon, perlu disirami dengan perhatian dan waktu.",
"Pacar itu seperti bantal, bisa menjadi tempat nyaman untuk bersandar.",
"Jika kamu ingin bahagia, belajarlah untuk menikmati setiap momen dalam hidupmu.",
"Ketika kamu merasa cemas, cobalah fokus pada hal-hal yang kamu bisa kendalikan.",
"Hidup ini seperti pesta, ada waktu untuk bersenang-senang dan ada waktu untuk istirahat.",
"Cinta itu seperti hobi, bisa membuatmu merasa hidup dan bersemangat.",
"Pacar itu seperti kopi, bisa memberi energi tapi jangan sampai membuatmu kelebihan dosis.",
"Jika kamu nggak tahu harus ngomong apa, coba deh bertanya tentang keinginan atau impian mereka.",
"Ketika kamu merasa kesal, ingatlah bahwa kamu memiliki kontrol atas reaksi dan emosimu.",
"Hidup ini seperti pohon bambu, perlu waktu untuk tumbuh dan berkembang.",
"Cinta itu seperti bintang di langit, kadang harus menunggu lama untuk melihatnya.",
"Pacar itu seperti hujan, bisa membuat hari menjadi lebih segar.",
"Jika kamu ingin sukses, berani mengambil risiko adalah kunci kesuksesan.",
"Ketika kamu merasa bahagia, bagikan kebahagiaanmu dengan orang lain.",
"Hidup ini seperti permainan, kadang menang, kadang kalah, tapi yang penting adalah ikut bermain.",
"Cinta itu seperti surga di dunia, tempat di mana kamu merasa tenang dan penuh kasih sayang.",
"Pacar itu seperti foto, bisa membuatmu tersenyum saat melihatnya.",
"Jika kamu nggak tahu harus ngomong apa, coba deh ceritakan tentang kegiatan yang kamu nikmati.",
"Ketika kamu merasa lelah, ingatlah bahwa istirahat adalah penting untuk kesehatanmu.",
"Hidup ini seperti musim, ada waktu untuk bertumbuh dan ada waktu untuk beristirahat.",
"Cinta itu seperti puzzle, harus dicari dan disusun dengan hati-hati.",
"Pacar itu seperti buku, bisa membuka jendela dunia baru untukmu.",
"Jika kamu ingin merubah duniamu, mulailah dengan merubah pola pikirmu.",
"Ketika kamu merasa kesepian, ingatlah bahwa teman-teman selalu ada untukmu.",
"Hidup ini seperti alam, penuh dengan keindahan dan misteri yang menunggu untuk dijelajahi.",
"Cinta itu seperti ombak di pantai, datang dan pergi dengan ritme yang indah.",
"Pacar itu seperti pelabuhan, tempatmu bisa berlabuh dan merasa aman.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang hal-hal yang membuatnya tertawa.",
"Ketika kamu merasa bingung, ingatlah bahwa kamu punya kemampuan untuk mencari solusi.",
"Cinta itu seperti air sungai, selalu mengalir dan memberi kehidupan di sepanjang perjalanannya.",
"Pacar itu seperti sinar matahari di pagi hari, memberi energi untuk memulai hari dengan semangat.",
"Jika kamu ingin bahagia, pelajari untuk menerima dan menghargai dirimu sendiri.",
"Ketika kamu merasa lelah, istirahatlah. Bahkan tumbuhan juga butuh istirahat di malam hari.",
"Hidup ini seperti petualangan, kamu yang menentukan rute dan tantangan yang ingin kamu hadapi.",
"Cinta itu seperti bintang di langit malam, selalu ada walaupun tak selalu terlihat.",
"Pacar itu seperti air hujan, bisa membuat bumi menjadi subur dan produktif.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang hal-hal yang ingin dicapai dalam hidupnya.",
"Ketika kamu merasa frustasi, ingatlah bahwa kamu punya kekuatan untuk mengatasi hambatan.",
"Hidup ini seperti taman, kamu yang menanam benih dan merawatnya agar tumbuh menjadi indah.",
"Cinta itu seperti cermin, bisa membuatmu melihat dirimu sendiri dengan lebih jujur.",
"Pacar itu seperti bunga, harus dirawat agar tetap mekar dan indah.",
"Jika kamu ingin sukses, jangan takut untuk mencoba hal baru dan mengambil risiko.",
"Ketika kamu merasa kesal, cobalah mengendalikan emosimu dengan bernapas dalam-dalam.",
"Hidup ini seperti tarian, kamu yang menentukan irama dan gerakannya.",
"Cinta itu seperti matahari terbenam, indah tapi hanya berlangsung sebentar.",
"Pacar itu seperti tempat pelarian, tempatmu bisa menjadi dirimu sendiri tanpa takut dihakimi.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang pengalaman hidupnya yang paling berkesan.",
"Ketika kamu merasa lelah, istirahatlah. Bahkan bumi juga butuh istirahat di malam hari.",
"Hidup ini seperti catatan musik, kamu yang menentukan nada dan ritme yang ingin kamu mainkan.",
"Cinta itu seperti angin, kadang lembut kadang kencang, tapi selalu membuatmu merasa hidup.",
"Pacar itu seperti api unggun, bisa memberi kehangatan di malam hari.",
"Jika kamu ingin bahagia, belajarlah untuk mensyukuri apa yang kamu miliki saat ini.",
"Ketika kamu merasa kesepian, cobalah berinteraksi dengan orang lain dan mencari teman baru.",
"Hidup ini seperti lukisan, kamu yang menentukan warna dan bentuknya.",
"Cinta itu seperti peta harta karun, kamu yang harus mencari dan menggali untuk menemukannya.",
"Pacar itu seperti kado spesial, memberi kebahagiaan dan kejutan dalam hidupmu.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang impian terbesarnya.",
"Ketika kamu merasa bingung, ingatlah bahwa kamu punya kemampuan untuk belajar dan berkembang.",
"Hidup ini seperti permainan catur, harus membuat langkah cerdas untuk mencapai tujuan.",
"Cinta itu seperti mata air, selalu mengalir dan memberi kehidupan di sekitarnya.",
"Pacar itu seperti cahaya bulan, memberi cahaya dan kehangatan di malam hari.",
"Jika kamu ingin merubah duniamu, mulailah dengan merubah pola pikir dan kebiasaanmu.",
"Ketika kamu merasa kesal, cobalah merenung sejenak sebelum bereaksi.",
"Hidup ini seperti petualangan, selalu ada hal baru yang menunggu untuk dijalani.",
"Cinta itu seperti tanaman, harus dirawat dengan penuh kasih sayang agar tumbuh dan berkembang.",
"Pacar itu seperti karya seni, harus dihargai dan dijaga dengan baik.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang pandangannya terhadap kehidupan.",
"Ketika kamu merasa lelah, ingatlah bahwa istirahat adalah penting untuk kesehatan fisik dan mentalmu.",
"Hidup ini seperti puzzle, kamu yang mencari potongan yang pas agar terbentuk gambar utuh.",
"Cinta itu seperti hujan lebat, bisa membuat hati menjadi basah tapi juga segar.",
"Pacar itu seperti teman dekat, selalu ada saat kamu butuh seseorang untuk berbicara.",
"Jika kamu ingin bahagia, belajarlah untuk menikmati proses dan perjalananmu.",
"Ketika kamu merasa cemas, cobalah bernapas dalam-dalam dan fokus pada momen saat ini.",
"Hidup ini seperti taman bunga, penuh dengan warna dan keindahan yang berbeda.",
"Cinta itu seperti ombak di laut, datang dan pergi dengan kekuatan yang tak terduga.",
"Pacar itu seperti pemandangan indah, bisa membuatmu merasa tenang dan terhibur.",
"Ketika kamu merasa frustasi, ingatlah bahwa kamu punya kekuatan untuk mengatasi rasa frustrasimu.",
"Hidup ini seperti tarian, kamu yang menentukan langkah dan gerakannya.",
"Cinta itu seperti embun pagi, memberi kesegaran pada hati dan pikiranmu.",
"Pacar itu seperti bantal, tempat untuk beristirahat dan bersantai setelah seharian beraktivitas.",
"Jika kamu ingin sukses, jangan pernah takut untuk menghadapi tantangan dan belajar dari kegagalan.",
"Ketika kamu merasa bahagia, bagikan kebahagiaanmu kepada orang-orang di sekitarmu.",
"Hidup ini seperti pohon, harus diberi perawatan dan nutrisi agar tumbuh kuat dan sehat.",
"Cinta itu seperti lagu, bisa mengalun indah di hatimu.",
"Pacar itu seperti bunga, harus diberi perhatian agar tetap mekar.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang hobi dan minatnya.",
"Ketika kamu merasa lelah, ingatlah bahwa istirahat adalah hal yang penting.",
"Cinta itu seperti matahari, selalu memberi cahaya dan kehangatan.",
"Pacar itu seperti kado istimewa, memberi kebahagiaan dan kejutan dalam hidupmu.",
"Jika kamu ingin merubah duniamu, mulailah dengan merubah cara berpikirmu.",
"Ketika kamu merasa kesepian, ingatlah bahwa ada orang-orang yang peduli dan ingin mendengarkanmu.",
"Hidup ini seperti permainan, kamu yang menentukan bagaimana kamu ingin memainkannya.",
"Cinta itu seperti air sungai, selalu mengalir dan memberi kehidupan.",
"Pacar itu seperti cahaya bulan, memberi cahaya di malam hari.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang impian dan tujuannya.",
"Hidup ini seperti petualangan, selalu ada sesuatu yang menunggu untuk dijelajahi.",
"Cinta itu seperti bunga matahari, selalu mengikuti arah cahaya.",
"Pacar itu seperti cinta pertama, takkan pernah terlupakan.",
"Jika kamu ingin bahagia, belajarlah untuk mensyukuri hal-hal kecil dalam hidup.",
"Ketika kamu merasa lelah, cobalah istirahat sejenak untuk mengisi ulang energimu.",
"Hidup ini seperti tarian, kamu yang menentukan langkah dan iramanya.",
"Cinta itu seperti mimpi indah, membuatmu tersenyum dalam tidurmu.",
"Pacar itu seperti pelukan hangat, memberi rasa aman dan nyaman.",
"Ketika kamu merasa kesal, ingatlah bahwa kamu bisa mencari cara untuk mengatasinya.",
"Cinta itu seperti tanaman, perlu disirami dengan perhatian agar tumbuh dan berkembang.",
"Pacar itu seperti cahaya bulan, memberi keindahan dalam malam gelap.",
"Jika kamu ingin sukses, berani mengambil langkah pertama adalah kuncinya.",
"Hidup ini seperti perjalanan, kamu yang menentukan rute dan tujuanmu.",
"Cinta itu seperti angin, tak bisa dilihat tapi bisa dirasakan.",
"Pacar itu seperti hujan lembut, bisa membuat hatimu menjadi segar.",
"Ketika kamu merasa lelah, cobalah untuk beristirahat dan mengisi ulang energimu.",
"Hidup ini seperti taman bunga, penuh dengan berbagai macam warna dan aroma.",
"Cinta itu seperti cahaya matahari, selalu ada walaupun terkadang terhalang awan.",
"Pacar itu seperti buku yang selalu menarik untuk dibaca lagi dan lagi.",
"Jika kamu ingin bahagia, pelajari untuk menghargai momen kecil dalam hidupmu.",
"Ketika kamu merasa cemas, cobalah bernapas dalam-dalam untuk menenangkan dirimu.",
"Hidup ini seperti musik, kamu yang menentukan irama dan liriknya.",
"Cinta itu seperti embun di pagi hari, memberi kesegaran pada hati dan pikiranmu.",
"Pacar itu seperti pelabuhan yang aman, tempatmu bisa berlindung dan merasa tenang.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang mimpi-mimpi masa depannya.",
"Ketika kamu merasa frustasi, ingatlah bahwa kamu punya kemampuan untuk mengatasi rasa frustrasimu.",
"Hidup ini seperti perjalanan, selalu ada hal baru yang bisa kamu temukan.",
"Cinta itu seperti aliran sungai, tak pernah berhenti mengalir.",
"Pacar itu seperti cahaya bulan, selalu memberi cahaya di tengah kegelapan.",
"Ketika kamu merasa kesepian, ingatlah bahwa ada orang-orang yang peduli padamu.",
"Hidup ini seperti permainan, kamu yang menentukan aturan dan strategimu.",
"Cinta itu seperti bunga, perlu dirawat agar tetap indah.",
"Pacar itu seperti sinar matahari, memberi kehangatan dalam hidupmu.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang pandangannya terhadap cinta.",
"Ketika kamu merasa lelah, cobalah istirahat untuk mengembalikan energimu.",
"Cinta itu seperti musim semi, memberi kehidupan dan keceriaan.",
"Pacar itu seperti sahabat dekat, selalu ada saat kamu butuh teman bicara.",
"Jika kamu ingin bahagia, belajarlah untuk bersyukur atas apa yang kamu miliki.",
"Ketika kamu merasa lelah, cobalah istirahat sejenak untuk mengembalikan energimu.",
"Cinta itu seperti air hujan, selalu memberi kesegaran pada hati dan pikiranmu.",
"Pacar itu seperti bantal lembut, tempatmu bisa bersantai dan beristirahat.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang hal-hal yang disukai.",
"Cinta itu seperti matahari terbenam, selalu memberi cahaya indah di akhir hari.",
"Pacar itu seperti teman sejati, selalu ada saat kamu butuh dukungan.",
"Ketika kamu merasa bahagia, bagikan kebahagiaanmu kepada orang lain.",
"Hidup ini seperti taman, penuh dengan bunga yang indah dan harum.",
"Cinta itu seperti embun pagi, memberi kesegaran pada hati dan pikiran.",
"Pacar itu seperti pelabuhan, tempatmu bisa berlindung dan merasa aman.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang mimpi dan tujuannya.",
"Hidup ini seperti musik, kamu yang menentukan nada dan iramanya.",
"Cinta itu seperti matahari terbit, selalu membawa harapan baru setiap pagi.",
"Pacar itu seperti bantal empuk, memberi tempat untuk beristirahat setelah seharian beraktivitas.",
"Ketika kamu merasa kesepian, ingatlah bahwa ada orang yang peduli padamu.",
"Cinta itu seperti air hujan, memberi kehidupan pada hati dan pikiranmu.",
"Pacar itu seperti cahaya bulan, selalu ada di malam hari meski tak selalu terlihat.",
"Ketika kamu merasa lelah, istirahatlah. Bahkan bunga pun butuh istirahat untuk mekar lagi.",
"Hidup ini seperti taman bunga, penuh dengan bunga yang berbeda-beda.",
"Cinta itu seperti sinar matahari, memberi cahaya dan kehangatan dalam hidupmu.",
"Pacar itu seperti pelabuhan, tempatmu bisa bersandar dan merasa aman.",
"Jika kamu ingin bahagia, belajarlah untuk mensyukuri apa yang kamu miliki.",
"Ketika kamu merasa cemas, cobalah untuk bernapas dalam-dalam dan fokus pada saat ini.",
"Hidup ini seperti petualangan, selalu ada hal baru yang menunggu untuk dijelajahi.",
"Cinta itu seperti bunga, harus dirawat agar tetap mekar dan indah.",
"Pacar itu seperti matahari terbenam, memberi keindahan di akhir hari.",
"Jika kamu nggak tahu harus ngomong apa, coba deh tanya tentang impian masa depannya.",
"Ketika kamu merasa bingung, ingatlah bahwa kamu punya kemampuan untuk menemukan jawaban.",
"Pacar itu seperti bantal empuk, bisa menjadi tempat nyaman untuk beristirahat.",
"Hidup ini seperti taman, penuh dengan berbagai macam bunga yang indah.",
"Cinta itu seperti cahaya matahari, selalu memberi kehangatan dan keceriaan.",
"Pacar itu seperti teman sejati, selalu ada untukmu dalam suka dan duka.",
"Ketika kamu merasa lelah, istirahatlah. Bahkan bumi pun butuh istirahat di malam hari.",
"Cinta itu seperti bunga, perlu dirawat dengan penuh kasih sayang agar tetap mekar.",
"Ketika kamu merasa kesepian, ingatlah bahwa ada teman-teman yang peduli padamu.",
"Hidup ini seperti permainan, kamu yang menentukan aturan dan strateginya.",
"Pacar itu seperti pelabuhan yang aman, tempatmu bisa berlindung dari badai.",
"Ketika kamu merasa kesal, ingatlah bahwa kamu bisa mencari cara untuk mengatasi perasaan tersebut.",
"Hidup ini seperti tarian, kamu yang menentukan gerakan dan iramanya.",
"Pacar itu seperti bantal empuk, tempatmu bisa beristirahat dengan nyaman.",
"Ketika kamu merasa lelah, istirahatlah sejenak untuk mengembalikan energimu.",
"Hidup ini seperti perjalanan, selalu ada hal baru yang menunggu untuk dijelajahi.",
"Pacar itu seperti pelabuhan yang aman, tempatmu bisa bersandar dan merasa aman.",
"Ketika kamu merasa kesepian, ingatlah bahwa ada teman dan keluarga yang peduli padamu.",
"Cinta itu seperti bunga, perlu perawatan agar tetap indah dan mekar.",
"Pacar itu seperti cahaya bulan, selalu ada di saat malam tiba.",
"Ketika kamu merasa bingung, ingatlah bahwa ada banyak jawaban di sekitarmu.",
"Pacar itu seperti bantal empuk, bisa menjadi tempat nyaman untuk bersantai.",
"Cinta itu seperti cahaya matahari, selalu memberi cahaya dan keceriaan.",
"Hidup ini ibarat kanvas kosong, kamu yang menentukan gambaran yang akan di lukis.",
"Cinta itu seperti bunga mawar, indah tapi kadang juga bisa menyakitkan.",
"Pacar itu seperti pilihan makanan, kadang kamu ingin mencoba sesuatu yang berbeda.",
"Jika kamu ingin sukses, jangan takut untuk mencoba dan belajar dari kegagalan.",
"Ketika kamu merasa terjatuh, ingatlah bahwa kamu masih bisa bangkit kembali.",
"Hidup ini seperti buku, kamu yang menulis ceritanya dengan setiap pilihan yang kamu buat.",
"Cinta itu seperti musik, bisa mengiringi setiap langkah dalam hidupmu.",
"Pacar itu seperti sahabat yang juga bisa menjadi pasangan hidupmu.",
"Jika kamu nggak tahu harus ngomong apa, coba tanya tentang impian terbesarnya.",
"Ketika kamu merasa sendirian, ingatlah bahwa ada orang-orang yang peduli denganmu.",
"Hidup ini seperti perjalanan, dan setiap tantangan adalah bagian dari petualanganmu.",
"Cinta itu seperti lukisan indah, setiap sentuhan memberikan kehidupan padanya.",
"Pacar itu seperti tempat berlindung saat hujan turun, memberikan kehangatan dalam dinginnya.",
"Jika kamu ingin mencapai impianmu, teruslah berusaha tanpa kenal lelah.",
"Ketika kamu merasa kehilangan arah, renungkanlah dan temukan kembali tujuan hidupmu.",
"Hidup ini seperti drama, kamu yang menulis skenarionya dengan pilihan-pilihanmu.",
"Cinta itu seperti sinar matahari, selalu ada untuk menerangi hari-harimu.",
"Pacar itu seperti taman bunga, penuh warna-warni kebahagiaan.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang hal-hal yang membuatnya tersenyum.",
"Ketika kamu merasa lelah, beristirahatlah tetapi jangan menyerah.",
"Hidup ini seperti komedi, kadang-kadang tertawa adalah hal terbaik yang bisa kamu lakukan.",
"Cinta itu seperti ombak di pantai, kadang datang dengan tenang dan kadang datang dengan keras.",
"Pacar itu seperti kisah cinta dalam novel, penuh dengan momen manis dan tantangan.",
"Jika kamu ingin meraih impianmu, jangan biarkan rintangan menghalangimu.",
"Ketika kamu merasa frustasi, hibur dirimu dengan melakukan hal yang kamu sukai.",
"Hidup ini seperti peta harta karun, kamu yang menemukan petunjuk dan rahasia di sepanjang jalan.",
"Cinta itu seperti melodi indah, mengalun dalam hati tanpa henti.",
"Pacar itu seperti teman hidup, selalu ada untukmu dalam setiap fase kehidupan.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang cerita lucu atau kenangan bersama.",
"Ketika kamu merasa ragu, ingatlah bahwa kamu memiliki potensi yang luar biasa.",
"Hidup ini seperti tarian, kamu yang menari dengan semangat dan kebahagiaan.",
"Cinta itu seperti lukisan abstrak, sulit dijelaskan tapi penuh dengan emosi.",
"Pacar itu seperti peluk hangat, memberi kenyamanan dalam dinginnya malam.",
"Jika kamu ingin menjalani hidup dengan penuh makna, berbuatlah baik kepada orang lain.",
"Ketika kamu merasa terpuruk, ingatlah bahwa setiap hari adalah kesempatan untuk memulai lagi.",
"Hidup ini seperti kanvas langit saat matahari terbenam, penuh warna dan keindahan.",
"Cinta itu seperti permainan, kadang kamu menang dan kadang kamu kalah.",
"Pacar itu seperti tempat berlabuh, memberi rasa aman dan nyaman.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang hal yang membuatnya tertawa.",
"Ketika kamu merasa lelah, istirahatlah sejenak dan timbangkan kembali prioritasmu.",
"Hidup ini seperti novel, setiap halaman berisi cerita yang menarik.",
"Cinta itu seperti sinar bulan di malam hari, memberi cahaya dalam gelap.",
"Pacar itu seperti pemandangan indah, kamu ingin selalu melihatnya lagi dan lagi.",
"Jika kamu ingin sukses, belajarlah dari kesalahan dan terus berkembang.",
"Ketika kamu merasa kesepian, carilah teman yang bisa mengisi hari-harimu dengan keceriaan.",
"Hidup ini seperti permainan puzzle, kamu yang menyusun potongan-potongan menjadi kesatuan.",
"Cinta itu seperti angin, kadang lembut dan kadang keras.",
"Pacar itu seperti matahari di pagi hari, memberi semangat untuk memulai hari.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang pengalaman yang berkesan baginya.",
"Ketika kamu merasa putus asa, ingatlah bahwa setiap tantangan adalah kesempatan untuk tumbuh.",
"Hidup ini seperti lukisan alam, penuh dengan keindahan yang tak ternilai.",
"Cinta itu seperti kisah dongeng, penuh dengan keajaiban dan kemungkinan.",
"Pacar itu seperti pahlawan dalam cerita, selalu ada untuk melindungi dan mendukungmu.",
"Jika kamu ingin menjalani hidup dengan bahagia, jadilah sumber kebahagiaan bagi orang lain.",
"Ketika kamu merasa kehilangan arah, carilah inspirasi dari hal-hal yang kamu cintai.",
"Hidup ini seperti panggung teater, kamu yang memerankan peran utamamu.",
"Cinta itu seperti percikan api, bisa tumbuh dari api kecil menjadi cinta yang besar.",
"Pacar itu seperti cahaya bintang di malam hari, selalu ada untuk memberi petunjuk.",
"Jika kamu nggak tahu harus ngomong apa, coba tanya tentang cita-citanya di masa depan.",
"Ketika kamu merasa kesal, ingatlah bahwa perasaan tersebut akan berlalu.",
"Hidup ini seperti petualangan, kamu yang menemukan keajaiban di setiap langkah.",
"Cinta itu seperti puisi indah, mengalir dengan kata-kata penuh makna.",
"Pacar itu seperti matahari di tengah hari, memberi energi untuk menjalani aktivitasmu.",
"Jika kamu ingin mencapai impianmu, berani mengambil risiko adalah langkah pertama.",
"Ketika kamu merasa cemas, cobalah untuk merenung dan mencari solusi.",
"Cinta itu seperti lukisan pemandangan, setiap detailnya memiliki keindahan sendiri.",
"Pacar itu seperti teman sejati, selalu ada dalam suka dan duka.",
"Jika kamu nggak tahu harus ngomong apa, coba tanya tentang hal yang membuatnya tertarik.",
"Ketika kamu merasa lelah, istirahatlah dan perhatikan kesehatanmu.",
"Hidup ini seperti lukisan abstrak, penuh dengan makna yang berbeda-beda bagi setiap orang.",
"Cinta itu seperti matahari terbenam, memberi kehangatan di akhir hari.",
"Pacar itu seperti bantal empuk, tempat beristirahat setelah hari yang panjang.",
"Jika kamu ingin meraih sukses, jangan takut untuk bekerja keras dan terus belajar.",
"Ketika kamu merasa sendirian, ingatlah bahwa kamu selalu punya dirimu sendiri.",
"Hidup ini seperti novel misteri, setiap halaman mengungkapkan rahasia baru.",
"Cinta itu seperti musik, bisa membuat hati bergetar dan emosi berpadu.",
"Pacar itu seperti pelukan hangat, memberi kenyamanan dan keamanan.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang pengalaman terindah dalam hidupnya.",
"Ketika kamu merasa putus asa, ingatlah bahwa setiap masalah memiliki solusinya.",
"Hidup ini seperti lagu, setiap kata menciptakan melodi dalam perjalananmu.",
"Cinta itu seperti lukisan pemandangan, setiap detilnya mengandung keindahan yang unik.",
"Pacar itu seperti bintang di langit, selalu bersinar dalam kegelapan.",
"Ketika kamu merasa kesepian, temukan teman sejati yang bisa mengisi kekosonganmu.",
"Hidup ini seperti petualangan, kamu yang menentukan jalur dan tujuanmu.",
"Cinta itu seperti hujan di musim panas, memberi kesegaran dan kebahagiaan.",
"Pacar itu seperti pelabuhan aman, tempatmu kembali setelah menjelajahi dunia.",
"Jika kamu nggak tahu harus ngomong apa, coba tanya tentang hal-hal yang membuatnya tersenyum.",
"Ketika kamu merasa lelah, istirahatlah dan perhatikan kesehatan fisik dan mentalmu.",
"Hidup ini seperti novel romansa, setiap bab mengandung cerita cinta yang unik.",
"Cinta itu seperti lukisan abstrak, kadang sulit diartikan tapi penuh dengan emosi.",
"Pacar itu seperti matahari di pagi hari, memberi semangat untuk memulai hari dengan positif.",
"Jika kamu ingin meraih impianmu, berani mengambil langkah pertama adalah kunci.",
"Ketika kamu merasa frustasi, cobalah untuk fokus pada hal-hal yang kamu kuasai.",
"Hidup ini seperti kanvas kosong, kamu yang menambahkan warna dan bentuk sesuai keinginanmu.",
"Cinta itu seperti musik, setiap nada menggambarkan perasaan yang berbeda.",
"Pacar itu seperti cahaya di tengah kegelapan, selalu memberi arah dalam hidupmu.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang rencana dan tujuannya di masa depan.",
"Ketika kamu merasa kebingungan, ingatlah bahwa setiap langkah adalah bagian dari perjalananmu.",
"Hidup ini seperti taman bermain, penuh dengan ups and downs yang membuatmu berteriak dan tertawa.",
"Cinta itu seperti hujan, kadang datang tiba-tiba dan merendahkan hatimu.",
"Pacar itu seperti layangan, jika tidak dipegang erat-erat bisa terbang menjauh.",
"Jika kamu ingin sukses, bersiaplah untuk menghadapi hujan badai dalam perjalananmu.",
"Ketika kamu merasa putus asa, ingatlah bahwa harapan selalu ada di ujung jalan.",
"Hidup ini seperti novel thriller, setiap halaman berisi kejutan yang tak terduga.",
"Cinta itu seperti misteri, harus dipecahkan dengan hati dan pikiran yang bijak.",
"Pacar itu seperti jembatan, membawa kamu dari satu fase hidup ke fase berikutnya.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang impian terbesarnya dan kemauan untuk meraihnya.",
"Ketika kamu merasa kesal, hembuskan nafas dalam-dalam dan hitung sampai sepuluh.",
"Cinta itu seperti obat, bisa menyembuhkan atau malah membuatmu lebih sakit.",
"Pacar itu seperti buku, kamu akan selalu menemukan hal baru setiap kali membacanya.",
"Jika kamu ingin sukses, berhenti membandingkan dirimu dengan orang lain.",
"Ketika kamu merasa terpuruk, carilah inspirasi dari orang-orang yang telah berhasil.",
"Hidup ini seperti roller coaster, penuh dengan kejutan dan sensasi.",
"Cinta itu seperti bunga, perlu dirawat dengan hati-hati agar tetap berbunga indah.",
"Pacar itu seperti musuh terbaik, selalu jujur meski terkadang menyakitkan.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang kelemahan dan usaha untuk memperbaikinya.",
"Ketika kamu merasa lelah, beristirahatlah sejenak dan nikmati momen keheningan.",
"Hidup ini seperti panggung drama, kamu yang berperan sebagai pemeran utama.",
"Cinta itu seperti permainan api, jika tidak dijaga bisa meluas dan membakar segalanya.",
"Pacar itu seperti rumah, harus dijaga dengan penuh perhatian agar tetap nyaman.",
"Jika kamu ingin mencapai impianmu, berani mengambil tindakan adalah langkah pertama.",
"Ketika kamu merasa sendirian, cari teman sejati yang selalu ada dalam suka dan duka.",
"Hidup ini seperti melodi, kamu yang menambahkan not-not indah di sepanjang perjalanan.",
"Cinta itu seperti puzzle, harus disusun dengan hati-hati agar sesuai dengan gambaran.",
"Pacar itu seperti air, kadang bisa menyegarkan dan kadang bisa tenggelamkan.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang cita-cita terbesarnya dan rencana untuk mencapainya.",
"Ketika kamu merasa frustasi, cobalah untuk berbicara dengan orang yang bisa mendengarkanmu.",
"Hidup ini seperti seni, kamu yang menciptakan karya indah di setiap langkahmu.",
"Cinta itu seperti mimpi, bisa membuatmu terbang ke langit atau jatuh ke jurang.",
"Pacar itu seperti pelukan hangat di malam dingin, memberi rasa aman dalam ketidakpastian.",
"Jika kamu ingin meraih kesuksesan, tetap fokus pada tujuanmu meski hujan badai menghadang.",
"Ketika kamu merasa putus asa, ingatlah bahwa setiap hari adalah kesempatan baru untuk memulai.",
"Hidup ini seperti novel fantasi, kamu yang menciptakan dunia ajaib dalam pikiranmu.",
"Cinta itu seperti musim, ada waktu untuk mekar dan waktu untuk gugur.",
"Pacar itu seperti kamera, merekam kenangan indah yang akan selalu dikenang.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang perjalanan hidupnya dan hikmah yang didapat.",
"Ketika kamu merasa kesepian, jangan ragu untuk mencari teman yang bisa menghiburmu.",
"Hidup ini seperti petualangan luar angkasa, penuh dengan misteri dan eksplorasi.",
"Cinta itu seperti lukisan, setiap goresan memberi kehidupan pada kanvas.",
"Pacar itu seperti kompas, memberi arah dalam setiap keputusan yang kamu ambil.",
"Jika kamu ingin meraih impianmu, tetap tekun dan jangan pernah menyerah.",
"Ketika kamu merasa frustasi, cobalah untuk berbicara dengan seseorang yang bisa memberimu perspektif baru.",
"Hidup ini seperti film, kamu yang menulis skenario dan memilih peranmu.",
"Cinta itu seperti cahaya di tengah kegelapan, selalu memberi harapan.",
"Pacar itu seperti puzlle, harus diselesaikan dengan sabar agar sesuai dengan gambaran.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang keberhasilan dan kegagalan dalam hidupnya.",
"Ketika kamu merasa kesal, cobalah untuk merenung sejenak sebelum merespon.",
"Hidup ini seperti lukisan abstrak, setiap orang memiliki interpretasi yang berbeda-beda.",
"Cinta itu seperti bintang di langit, kadang terlihat jauh tapi selalu ada di sana.",
"Pacar itu seperti lentera, memberi cahaya dalam kegelapan hidupmu.",
"Ketika kamu merasa sendirian, ingatlah bahwa kamu memiliki teman sejati di dalam dirimu.",
"Hidup ini seperti perjalanan kereta api, penuh dengan stasiun-stasiun kehidupan yang berbeda.",
"Cinta itu seperti pesta, kadang meriah tapi juga bisa meninggalkan kerinduan.",
"Pacar itu seperti cinta pertama, sulit untuk dilupakan meski telah berlalu.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang hal-hal yang membuatnya tertawa terbahak-bahak.",
"Ketika kamu merasa lelah, istirahatlah dan perhatikan kesehatan mentalmu.",
"Hidup ini seperti taman bunga, kamu yang menanam biji kebaikan untuk panen di masa depan.",
"Cinta itu seperti lukisan senja, penuh dengan warna-warni indah yang lembut.",
"Pacar itu seperti musik, mengiringi setiap langkah hidupmu dengan indah.",
"Jika kamu ingin sukses, jadilah pemimpin bagi dirimu sendiri dan tetap konsisten.",
"Ketika kamu merasa frustasi, carilah cara untuk melepaskan emosi tanpa menyakiti diri sendiri atau orang lain.",
"Hidup ini seperti perjalanan laut, terkadang tenang dan terkadang berombak.",
"Cinta itu seperti puzzle, setiap bagian mengisi kekosongan dalam hatimu.",
"Pacar itu seperti cermin, akan memantulkan kembali apa yang kamu berikan.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang pengalaman yang paling berharga dalam hidupnya.",
"Ketika kamu merasa kebingungan, cobalah untuk merenung dan mencari jawaban dalam dirimu sendiri.",
"Hidup ini seperti tarian hujan, bisa menjadi pelarian dari rutinitas.",
"Cinta itu seperti rahasia, perlahan terbongkar dan mengubah hidupmu.",
"Pacar itu seperti musuh terburuk, tidak pernah takut untuk mengatakan kebenaran.",
"Jika kamu ingin meraih impianmu, bekerja keraslah tanpa terganggu oleh keraguan orang lain.",
"Ketika kamu merasa putus asa, cobalah untuk melihat sisi positif dari segala situasi.",
"Hidup ini seperti kolam renang, kamu yang memutuskan apakah akan berenang atau hanya berdiam di pinggir.",
"Cinta itu seperti sinar matahari, hangatkan hati dan memberi energi.",
"Pacar itu seperti selembar kertas putih, kamu yang menuliskan cerita bersamanya.",
"Jika kamu nggak tahu harus ngomong apa, coba tanya tentang hal-hal yang paling menginspirasinya.",
"Ketika kamu merasa kesepian, jangan ragu untuk mencari teman yang bisa mendengarkan.",
"Hidup ini seperti permainan catur, kamu yang harus berpikir strategis dalam setiap langkah.",
"Cinta itu seperti bunga mawar, indah tapi bisa menyakiti dengan duri-durinya.",
"Pacar itu seperti petir di langit biru, bisa muncul dengan tiba-tiba dan menggelegar.",
"Jika kamu ingin bahagia, belajarlah untuk menghargai momen-momen kecil dalam hidupmu.",
"Ketika kamu merasa frustasi, cobalah untuk mencari solusi daripada hanya menyalahkan diri sendiri.",
"Hidup ini seperti bermain kartu, kamu yang menentukan kapan harus bertaruh dan kapan harus mundur.",
"Cinta itu seperti lukisan abstrak, sulit dijelaskan tapi bisa meninggalkan kesan mendalam.",
"Pacar itu seperti bantal empuk, tempatmu bercengkerama dan berbagi cerita.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang hal yang paling mengganggunya saat ini.",
"Ketika kamu merasa lelah, istirahatlah dan nikmati momen ketenangan.",
"Hidup ini seperti perjalanan hiking, penuh dengan tantangan namun juga pemandangan indah.",
"Cinta itu seperti novel roman, setiap halaman mengandung cerita yang mendebarkan.",
"Pacar itu seperti peta harta karun, kamu yang menemukan keunikan dan kelebihannya.",
"Jika kamu ingin meraih impianmu, pertahankan fokusmu meski ada godaan untuk menyerah.",
"Ketika kamu merasa sendirian, cari teman yang bisa membuatmu merasa diterima apa adanya.",
"Hidup ini seperti sinetron, setiap hari ada drama yang berbeda.",
"Cinta itu seperti melodi piano, indah saat dimainkan dengan hati.",
"Pacar itu seperti baju, kamu harus merawatnya agar tetap cocok dan nyaman.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang hobi dan passion-nya.",
"Ketika kamu merasa kesal, cobalah untuk menenangkan diri sejenak sebelum bereaksi.",
"Hidup ini seperti alam semesta, penuh dengan planet-planet kehidupan yang beragam.",
"Cinta itu seperti film romantis, kadang manis tapi juga kadang pahit.",
"Pacar itu seperti kunci, membuka pintu hatimu untuk orang yang pantas masuk.",
"Jika kamu ingin sukses, berani mengambil risiko adalah langkah pertama.",
"Ketika kamu merasa putus asa, ingatlah bahwa setiap tantangan adalah kesempatan untuk berkembang.",
"Hidup ini seperti taman bermain, penuh dengan permainan yang menguji keberanianmu.",
"Cinta itu seperti api unggun, bisa memberi hangat tapi juga bisa membakar.",
"Pacar itu seperti puisi, penuh dengan kata-kata indah yang mengalir.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang impian terbesarnya dan langkah yang sudah diambil untuk mewujudkannya.",
"Hidup ini seperti perjalanan pelayaran, kamu yang menentukan arah kapalmu.",
"Cinta itu seperti hujan musim semi, memberi kesegaran setelah kehausan panjang.",
"Pacar itu seperti bintang jatuh, sulit untuk menemukan tapi berharga saat ditemukan.",
"Jika kamu ingin meraih impianmu, berjuanglah meski banyak rintangan di depanmu.",
"Ketika kamu merasa frustasi, carilah cara untuk melepaskan emosi dengan sehat.",
"Hidup ini seperti lukisan pemandangan, setiap detilnya memiliki keindahan tersendiri.",
"Cinta itu seperti angin, kamu tidak bisa melihatnya tapi bisa merasakannya.",
"Pacar itu seperti catatan harian, menyimpan kenangan indah dalam hidupmu.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang pengalaman paling lucu yang pernah dialaminya.",
"Ketika kamu merasa sendirian, carilah teman yang bisa mengisi kekosongan dalam hatimu.",
"Hidup ini seperti novel petualangan, setiap bab membawa kamu ke tempat yang baru.",
"Cinta itu seperti tarian, kamu yang menentukan langkah dan iramanya.",
"Pacar itu seperti pelabuhan, tempatmu kembali setelah menjelajahi dunia.",
"Jika kamu ingin sukses, bersiaplah untuk belajar dari kegagalanmu.",
"Ketika kamu merasa putus asa, ingatlah bahwa masa sulit akan berlalu.",
"Hidup ini seperti taman bunga, penuh dengan warna-warni indah yang perlu dinikmati.",
"Cinta itu seperti puisi, hanya bisa dimengerti oleh mereka yang merasakannya.",
"Pacar itu seperti gelombang laut, kadang tenang dan kadang mengguncang.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang cita-cita terbesarnya dan langkah apa yang sudah diambil untuk mencapainya.",
"Ketika kamu merasa lelah, beristirahatlah dan perhatikan kesehatanmu.",
"Hidup ini seperti peta, kamu yang menentukan jalur dan tujuanmu.",
"Cinta itu seperti mimpi indah, membuat hatimu berbunga-bunga.",
"Pacar itu seperti peluk, memberi kenyamanan dalam segala suasana.",
"Jika kamu ingin meraih impianmu, tetap fokus dan kerja keraslah.",
"Ketika kamu merasa frustasi, carilah cara untuk meredakan stres dengan positif.",
"Hidup ini seperti perjalanan, kamu yang memilih arah dan destinasi.",
"Cinta itu seperti senyuman, bisa mengubah hari yang kelabu menjadi cerah.",
"Pacar itu seperti kamera, merekam momen-momen indah dalam hidupmu.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang hal yang paling menginspirasinya dalam hidup.",
"Ketika kamu merasa kesal, cobalah untuk mengendalikan emosi sebelum bertindak.",
"Hidup ini seperti permainan catur, kamu yang harus berpikir strategis dalam setiap langkahmu.",
"Cinta itu seperti lukisan, setiap goresan menggambarkan cerita yang berbeda.",
"Pacar itu seperti penerang jalan, membimbingmu melalui kegelapan hidup.",
"Jika kamu ingin bahagia, carilah kebahagiaan dalam diri sendiri sebelum mencarinya di tempat lain.",
"Ketika kamu merasa sendirian, ingatlah bahwa kamu memiliki dirimu sendiri.",
"Hidup ini seperti makanan lezat, penuh dengan rasa dan kenangan yang manis.",
"Cinta itu seperti lukisan pemandangan, kamu yang menambahkan warna dalam hidupnya.",
"Pacar itu seperti rumah, tempatmu berlindung dan merasa aman.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang keinginannya dalam jangka panjang.",
"Ketika kamu merasa lelah, beristirahatlah dan nikmati momen kedamaian.",
"Hidup ini seperti pertunjukan teater, kamu yang berperan sebagai bintang utama.",
"Cinta itu seperti lagu, menciptakan melodi indah dalam hati.",
"Pacar itu seperti cermin, mencerminkan siapa kamu sebenarnya.",
"Jika kamu ingin meraih impianmu, berani mengambil risiko dan berusaha keras.",
"Ketika kamu merasa putus asa, ingatlah bahwa setiap hari adalah peluang baru.",
"Hidup ini seperti petualangan, kamu yang menentukan bagaimana ceritanya.",
"Cinta itu seperti sinar matahari, menerangi hari-harimu.",
"Pacar itu seperti catatan harian, berisi kenangan-kenangan indah bersamamu.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang pengalaman paling berkesan yang pernah dialaminya.",
"Ketika kamu merasa kesepian, carilah teman yang bisa mengisi kekosongan dalam hatimu.",
"Hidup ini seperti taman bermain, penuh dengan kegembiraan dan tantangan.",
"Cinta itu seperti bintang di langit malam, memberi cahaya dalam kegelapan.",
"Pacar itu seperti teman terbaik, selalu ada dalam suka dan duka.",
"Jika kamu ingin meraih impianmu, berjuanglah tanpa ragu dan kecewa.",
"Ketika kamu merasa frustasi, carilah cara untuk mengatasi perasaan tersebut.",
"Hidup ini seperti perjalanan kereta api, penuh dengan perhentian yang menarik.",
"Cinta itu seperti novel drama, penuh dengan kisah yang menguras emosi.",
"Pacar itu seperti sepotong puzzle, kamu yang menambahkan potongan demi potongan hingga menjadi satu kesatuan.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang impian masa depannya dan rencana untuk mencapainya.",
"Ketika kamu merasa lelah, istirahatlah dan nikmati momen kedamaian.",
"Hidup ini seperti film komedi, kadang harus tertawa dalam situasi sulit.",
"Cinta itu seperti lukisan abstrak, setiap orang memiliki interpretasi yang berbeda.",
"Pacar itu seperti pelukan hangat, memberi kenyamanan dalam setiap pelukan.",
"Jika kamu ingin meraih impianmu, terus berusaha meski ada rintangan.",
"Ketika kamu merasa sendirian, carilah teman yang bisa menghiburmu.",
"Hidup ini seperti tarian, setiap langkah menggambarkan perjalananmu.",
"Cinta itu seperti musik, indah saat dimainkan dengan perasaan.",
"Pacar itu seperti bunga mawar, indah tapi bisa menyakiti dengan duri-durinya.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang kebahagiaannya saat ini.",
"Ketika kamu merasa frustasi, carilah jalan keluar daripada memendam perasaan tersebut.",
"Hidup ini seperti alur cerita, kamu yang memutuskan bagaimana ceritamu akan berjalan.",
"Cinta itu seperti matahari terbit, memberi cahaya di awal hari.",
"Pacar itu seperti bantal empuk, tempat beristirahat setelah lelah.",
"Jika kamu ingin bahagia, pelajari untuk mensyukuri hal-hal kecil dalam hidup.",
"Ketika kamu merasa kesal, carilah cara untuk mengatasi emosi dengan bijak.",
"Cinta itu seperti petir di langit biru, bisa datang secara tak terduga.",
"Pacar itu seperti makanan favoritmu, selalu memberi kenikmatan dalam hidup.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang rencana masa depannya.",
"Ketika kamu merasa lelah, beristirahatlah dan luangkan waktu untuk dirimu sendiri.",
"Hidup ini seperti pelayaran, kamu yang menentukan arah kapalmu.",
"Cinta itu seperti senyum, bisa membuat hari-hari menjadi lebih cerah.",
"Pacar itu seperti buku, selalu ada hal baru yang bisa kamu pelajari darinya.",
"Jika kamu ingin meraih impianmu, tetap konsisten dan berjuang tanpa henti.",
"Ketika kamu merasa putus asa, ingatlah bahwa setiap tantangan adalah peluang untuk tumbuh.",
"Hidup ini seperti lukisan pemandangan, kamu yang menambahkan warna-warni indah dalamnya.",
"Cinta itu seperti bunga, butuh perawatan agar tetap mekar.",
"Pacar itu seperti peta, membawa kamu ke tempat-tempat baru dalam hidup.",
"Hidup ini seperti permainan puzzle, kamu yang harus mencari bagian yang cocok.",
"Cinta itu seperti sinar matahari, memberi cahaya dalam hidupmu.",
"Pacar itu seperti cermin, mencerminkan siapa dirimu sebenarnya.",
"Jika kamu ingin meraih impianmu, tetap semangat dan jangan pernah menyerah.",
"Hidup ini seperti taman bermain, penuh dengan kegembiraan dan tawa.",
"Cinta itu seperti hujan musim semi, membawa segar setelah dingin.",
"Pacar itu seperti sahabat dekat, selalu ada dalam setiap momen penting.",
"Jika kamu nggak tahu harus ngomong apa, tanya tentang impian masa depannya.",
"Hidup ini seperti film petualangan, kamu yang menentukan jalan ceritanya.",
"Cinta itu seperti lagu, menciptakan harmoni dalam hidup.",
"Jika kamu ingin meraih impianmu, tetap fokus dan berusaha keras.",
"Ketika kamu merasa putus asa, ingatlah bahwa setiap hari adalah kesempatan baru.",
"Hidup ini seperti alam semesta, penuh dengan misteri dan keindahan.",
"Cinta itu seperti angin, kadang lembut dan kadang kencang.",
"Pacar itu seperti rumah, tempat berlindung dan merasa aman."
];
